---
- hosts: yandex
  become: true
  gather_facts: no

  tasks:
  - name: "Create user"
    shell: "sudo useradd user2"
    tags: 'add_user'

  - name: "Copy ssh key"
    ansible.builtin.copy:
      src: "~/.ssh/id_rsa.pub" 
      dest: "/home/user2/.ssh/"
    tags: 'ssh'